# -*- coding: utf-8 -*-
"""SentimentAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgd5qxRqT7cWIcgegRqj0Q9ymp2ImQSE
"""

import pandas as pd
import numpy as np

df = pd.read_csv("IMDBDataset.csv")

df.head()

df.isnull().sum()

df.drop_duplicates(inplace=True)

df.shape

#pre processinng
#1.Convert lowercase values
df["review"] = df["review"].str.lower()

import re

#sample_test = "abc is the word, abc" #abc => xyz
#new_text = re.sub("abc","xyz",sample_test)

def remove_url(text):
  re.sub(r"https/S+", "",text) #(pattern,repl,string) eg-https://www.google.com
  df["review"] = df["review"].apply(remove_url)

"""Remove punctuatiom"""

def remove_punctuations(text):
  re.sub(r"^A-Za-z0-9\s" , "",text)#A-Z a-z 0-9
  return text
  df["review"] = df["review"].apply(remove_punc)

#remove html tags
def remove_html(text):
  text = re.sub(r"<.*?","",text)
  return text
  df["review"] = df["review"].apply(remove_html)

#remove stop words
import nltk

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def remove_stopwords(text):
  tokens = word_tokenize(text)
  stop_words = stopwords.words("english")#check stopwords


  for word in tokens:
    if word in stopwords:
      text = text.replace(word,"")

  return text
  df["review"] = df["review"].apply(remove_stopwords)

df.head()

#Stemming
from nltk.stem import PorterStemmer

def stemming(text):
  ps = PorterStemmer()
  stemmed_words = []
  tokens = word_tokenize(text)
  for word in tokens:
    stemmed_token = ps.stem(tokens)
    stemmed_words.push(stemmed_token)

  return "".join(stemmed_words)

  df["review"] = df["review"].apply(stemming)

df.head()

#encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

y =df["sentiment"]

y

"""Vectorization"""

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features = 5000)
X = tf.fit_transform(df["review"])

X

print(X)

"""dataset and dataloader"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape

X_test.shape

X_train = X_train.toarray()
X_test = X_test.toarray()

import torch
from torch.utils.data import TensorDataset,DataLoader

train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

"""## BUILD RNN"""

import torch.nn as nn
import torch.optim as optim

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0)
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

"""#RNN LAYERS"""

input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

"""Training Layer"""

epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction

        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")
